name: Deploy FTP to DirectAdmin

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  SERVER_DIR: ./domains/ftpdeploy.hoshisky.com/public_html/

jobs:
  ftp-upload:
    name: Sync files via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          security: loose
          timeout: 190000
          log-level: verbose
          server-dir: ${{ env.SERVER_DIR }}
          exclude: |
            **/*
            !package.json
            !package-lock.json
            !index.js
